/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 artgallerymodel.gltf 
Author: lukasakerlind (https://sketchfab.com/lukasakerlind)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/art-gallery-592b976ca9974711926b3c28e0093c35
Title: Art Gallery
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/artgallerymodel.gltf')
  console.log(nodes?'ture':'false',materials)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[12480.451, 1781.184, 7195.597]} rotation={[Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Tavla_Ram_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Tavla_Bild_0.geometry} material={materials.Bild} />
            <mesh geometry={nodes.Tavla_Bak_0.geometry} material={materials.material_2} />
          </group>
          <group position={[26538.559, 1872.639, -12521.016]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes['Tavla001_Material_#14_0'].geometry} material={materials.Material_14} />
            <mesh geometry={nodes['Tavla001_Material_#15_0'].geometry} material={materials.Material_15} />
            <mesh geometry={nodes['Tavla001_Material_#16_0'].geometry} material={materials.Material_16} />
          </group>
          <group position={[14729.285, 1871.438, -12226.985]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes['Tavla002_Material_#19_0'].geometry} material={materials.Material_19} />
            <mesh geometry={nodes['Tavla002_Material_#20_0'].geometry} material={materials.Material_20} />
            <mesh geometry={nodes['Tavla002_Material_#17_0'].geometry} material={materials.Material_17} />
          </group>
          <group position={[6457.475, 1860.905, -12455.586]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes['Tavla003_Material_#22_0'].geometry} material={materials.Material_22} />
            <mesh geometry={nodes['Tavla003_Material_#24_0'].geometry} material={materials.Material_24} />
            <mesh geometry={nodes['Tavla003_Material_#23_0'].geometry} material={materials.Material_23} />
          </group>
          <group position={[2566.445, 1746.213, -17607.32]} scale={[2.09, 2.09, 1]}>
            <mesh geometry={nodes['Tavla004_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh geometry={nodes['Tavla004_Material_#27_0'].geometry} material={materials.Material_27} />
            <mesh geometry={nodes['Tavla004_Material_#26_0'].geometry} material={materials.Material_26} />
          </group>
          <group position={[-3899.77, 1816.622, -17607.32]} scale={[3.021, 3.021, 1]}>
            <mesh geometry={nodes['Tavla005_Material_#31_0'].geometry} material={materials.Material_31} />
            <mesh geometry={nodes['Tavla005_Material_#32_0'].geometry} material={materials.Material_32} />
            <mesh geometry={nodes['Tavla005_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group position={[10686.37, 1757.761, -7369.901]} scale={[3.617, 3.617, 1]}>
            <mesh geometry={nodes['Tavla006_Material_#36_0'].geometry} material={materials.Material_36} />
            <mesh geometry={nodes['Tavla006_Material_#35_0'].geometry} material={materials.Material_35} />
            <mesh geometry={nodes['Tavla006_Material_#33_0'].geometry} material={materials.Material_33} />
          </group>
          <group position={[-12651.449, 1704.256, 7195.593]} rotation={[Math.PI, 0, -Math.PI]} scale={[2.362, 2.362, 1]}>
            <mesh geometry={nodes['Tavla007_Material_#39_0'].geometry} material={materials.Material_39} />
            <mesh geometry={nodes['Tavla007_Material_#40_0'].geometry} material={materials.Material_40} />
            <mesh geometry={nodes['Tavla007_Material_#38_0'].geometry} material={materials.Material_38} />
          </group>
          <group position={[-10790.589, 1765.328, -9929.256]}>
            <mesh geometry={nodes['Tavla008_Material_#41_0'].geometry} material={materials.Material_41} />
            <mesh geometry={nodes['Tavla008_Material_#44_0'].geometry} material={materials.Material_44} />
            <mesh geometry={nodes['Tavla008_Material_#42_0'].geometry} material={materials.Material_42} />
          </group>
          <group position={[26538.559, 1763.71, 1519.409]} rotation={[0, -Math.PI / 2, 0]} scale={[0.773, 0.773, 1]}>
            <mesh geometry={nodes['Tavla009_Material_#48_0'].geometry} material={materials.Material_48} />
            <mesh geometry={nodes['Tavla009_Material_#45_0'].geometry} material={materials.Material_45} />
            <mesh geometry={nodes['Tavla009_Material_#46_0'].geometry} material={materials.Material_46} />
          </group>
          <mesh geometry={nodes['Walls_Material_#52_0'].geometry} material={materials.Material_52} position={[2047.289, 0, -8615.351]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Plane001_Floor_0.geometry} material={materials.Floor} position={[3238.412, 0, -4719.176]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Text001_Text_0.geometry} material={materials.Text} position={[-19136.053, 2404.43, -6837.067]} rotation={[0, -Math.PI / 2, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/artgallerymodel.gltf')
